-- ============================================================
--  TalentBridge Job Portal  –  Supabase / PostgreSQL Schema
--  Single canonical file. Run once in the SQL Editor.
--  Last revised: 2025
-- ============================================================

-- ── Extensions ───────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS vector;          -- pgvector for AI embeddings


-- ============================================================
--  TABLE: users
--  Central auth/identity record for every account.
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
  id            UUID         PRIMARY KEY DEFAULT uuid_generate_v4(),
  email         VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name     VARCHAR(255) NOT NULL,
  role          VARCHAR(20)  NOT NULL CHECK (role IN ('candidate', 'employer', 'admin')),
  is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);


-- ============================================================
--  TABLE: employer_profiles
--  Company details for employer accounts (1-to-1 with users).
-- ============================================================
CREATE TABLE IF NOT EXISTS employer_profiles (
  id                  UUID         PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id             UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  company_name        VARCHAR(255),
  company_description TEXT,
  industry            VARCHAR(100),
  company_size        VARCHAR(50),
  company_website     VARCHAR(255),
  company_logo        TEXT,
  headquarters        VARCHAR(255),
  founded_year        INTEGER,
  linkedin_url        VARCHAR(255),
  twitter_url         VARCHAR(255),
  created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  UNIQUE (user_id)
);


-- ============================================================
--  TABLE: candidate_profiles
--  Full profile for job-seeker accounts (1-to-1 with users).
--  The embedding column stores a 384-dim sentence vector
--  generated by all-MiniLM-L6-v2 for AI job matching.
-- ============================================================
CREATE TABLE IF NOT EXISTS candidate_profiles (
  id                  UUID         PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id             UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Personal details
  headline            VARCHAR(255),
  bio                 TEXT,
  profile_picture     TEXT,
  phone_number        TEXT,
  country_code        TEXT         NOT NULL DEFAULT '+91',
  date_of_birth       DATE,
  gender              TEXT,
  lives_in            TEXT,

  -- Professional details
  skills              TEXT[]       NOT NULL DEFAULT '{}',
  experience_years    INTEGER,
  education           TEXT,
  experience          TEXT,
  desired_job_title   VARCHAR(255),
  preferred_location  VARCHAR(255),
  preferred_category  VARCHAR(100),
  preferred_job_type  VARCHAR(50),
  desired_salary      TEXT,
  is_open_to_work     BOOLEAN      NOT NULL DEFAULT TRUE,

  -- Resume
  resume_url          TEXT,
  resume_key          TEXT,
  resume_filename     VARCHAR(255),
  resume_uploaded_at  TIMESTAMPTZ,
  resume_parsed       BOOLEAN      NOT NULL DEFAULT FALSE,
  resume_parsed_at    TIMESTAMPTZ,
  resume_parse_failed BOOLEAN      NOT NULL DEFAULT FALSE,

  -- Social links
  linkedin_url        VARCHAR(255),
  github_url          VARCHAR(255),
  portfolio_url       VARCHAR(255),

  -- AI matching vector (384-dim cosine)
  embedding           VECTOR(384),

  created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  UNIQUE (user_id)
);


-- ============================================================
--  TABLE: jobs
--  Job listings posted by employers.
--  embedding is generated at post time for AI candidate matching.
-- ============================================================
CREATE TABLE IF NOT EXISTS jobs (
  id                   UUID         PRIMARY KEY DEFAULT uuid_generate_v4(),
  employer_id          UUID         NOT NULL REFERENCES users(id)            ON DELETE CASCADE,
  employer_profile_id  UUID         REFERENCES employer_profiles(id)         ON DELETE SET NULL,

  -- Content
  title                VARCHAR(255) NOT NULL,
  description          TEXT         NOT NULL,
  requirements         TEXT,
  skills               TEXT[]       NOT NULL DEFAULT '{}',

  -- Classification
  location             VARCHAR(255),
  is_remote            BOOLEAN      NOT NULL DEFAULT FALSE,
  job_type             VARCHAR(50)  CHECK (job_type IN (
                          'full-time', 'part-time', 'contract', 'freelance', 'internship'
                        )),
  experience_level     VARCHAR(50)  CHECK (experience_level IN (
                          'entry', 'mid', 'senior', 'lead', 'executive'
                        )),
  category             VARCHAR(100),

  -- Compensation
  salary_min           INTEGER,
  salary_max           INTEGER,

  -- Lifecycle
  status               VARCHAR(20)  NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'closed', 'draft')),
  application_deadline TIMESTAMPTZ,
  views                INTEGER      NOT NULL DEFAULT 0,

  -- AI matching vector (384-dim cosine)
  embedding            VECTOR(384),

  created_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);


-- ============================================================
--  TABLE: applications
--  Tracks every candidate ↔ job application and its status.
-- ============================================================
CREATE TABLE IF NOT EXISTS applications (
  id             UUID         PRIMARY KEY DEFAULT uuid_generate_v4(),
  job_id         UUID         NOT NULL REFERENCES jobs(id)  ON DELETE CASCADE,
  candidate_id   UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  employer_id    UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  cover_letter   TEXT,
  resume_url     TEXT,

  status         VARCHAR(30)  NOT NULL DEFAULT 'pending' CHECK (
                   status IN ('pending', 'reviewing', 'shortlisted',
                              'interviewed', 'offered', 'rejected', 'withdrawn')
                 ),
  employer_notes TEXT,
  match_score    INTEGER,

  applied_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

  UNIQUE (job_id, candidate_id)
);


-- ============================================================
--  TABLE: saved_jobs
--  Bookmarked jobs per candidate.
-- ============================================================
CREATE TABLE IF NOT EXISTS saved_jobs (
  id       UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id  UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  job_id   UUID        NOT NULL REFERENCES jobs(id)  ON DELETE CASCADE,
  saved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, job_id)
);


-- ============================================================
--  TABLE: job_views
--  Per-impression analytics for each job listing.
-- ============================================================
CREATE TABLE IF NOT EXISTS job_views (
  id        UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  job_id    UUID        NOT NULL REFERENCES jobs(id)  ON DELETE CASCADE,
  viewer_id UUID        REFERENCES users(id)          ON DELETE SET NULL,
  viewed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
--  TABLE: password_reset_tokens
--  Short-lived SHA-256 hashed tokens for password resets.
-- ============================================================
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id         UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT        NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
--  TABLE: notifications
--  In-app + email notification records per user.
--  type values: application_received | application_status_changed |
--               job_match | job_saved | profile_viewed | system
-- ============================================================
CREATE TABLE IF NOT EXISTS notifications (
  id         UUID         PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id    UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type       VARCHAR(50)  NOT NULL,
  title      VARCHAR(255) NOT NULL,
  message    TEXT         NOT NULL,
  link       VARCHAR(500),
  is_read    BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);


-- ============================================================
--  INDEXES  –  standard B-tree
-- ============================================================

-- jobs
CREATE INDEX IF NOT EXISTS idx_jobs_employer_id   ON jobs (employer_id);
CREATE INDEX IF NOT EXISTS idx_jobs_status         ON jobs (status);
CREATE INDEX IF NOT EXISTS idx_jobs_category       ON jobs (category);
CREATE INDEX IF NOT EXISTS idx_jobs_created_at     ON jobs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_jobs_deadline       ON jobs (application_deadline)
  WHERE status = 'active';

-- applications
CREATE INDEX IF NOT EXISTS idx_apps_job_id         ON applications (job_id);
CREATE INDEX IF NOT EXISTS idx_apps_candidate_id   ON applications (candidate_id);
CREATE INDEX IF NOT EXISTS idx_apps_employer_id    ON applications (employer_id);
CREATE INDEX IF NOT EXISTS idx_apps_status         ON applications (status);

-- saved_jobs
CREATE INDEX IF NOT EXISTS idx_saved_jobs_user_id  ON saved_jobs (user_id);

-- job_views
CREATE INDEX IF NOT EXISTS idx_job_views_job_id    ON job_views (job_id);

-- profiles
CREATE INDEX IF NOT EXISTS idx_candidate_user_id   ON candidate_profiles (user_id);
CREATE INDEX IF NOT EXISTS idx_employer_user_id    ON employer_profiles  (user_id);

-- password_reset_tokens
CREATE INDEX IF NOT EXISTS idx_prt_token_hash      ON password_reset_tokens (token_hash);
CREATE INDEX IF NOT EXISTS idx_prt_user_id         ON password_reset_tokens (user_id);

-- notifications
CREATE INDEX IF NOT EXISTS idx_notif_user_id       ON notifications (user_id);
CREATE INDEX IF NOT EXISTS idx_notif_user_unread   ON notifications (user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_notif_created_at    ON notifications (created_at DESC);


-- ============================================================
--  INDEXES  –  HNSW vector (approximate nearest-neighbour)
--  Uses cosine distance to match the <=> operator in the
--  RPC functions below.
--  m=16 / ef_construction=64 is a good default for this scale.
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_jobs_embedding_hnsw
  ON jobs USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

CREATE INDEX IF NOT EXISTS idx_candidates_embedding_hnsw
  ON candidate_profiles USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);


-- ============================================================
--  VIEWS
-- ============================================================

-- jobs_with_company: active jobs enriched with employer details.
CREATE OR REPLACE VIEW jobs_with_company AS
SELECT
  j.*,
  ep.company_name,
  ep.company_logo,
  ep.company_website,
  ep.industry
FROM  jobs j
LEFT JOIN employer_profiles ep ON ep.id = j.employer_profile_id
WHERE j.status = 'active';


-- job_application_stats: aggregated funnel metrics per job.
CREATE OR REPLACE VIEW job_application_stats AS
SELECT
  j.id                                                         AS job_id,
  j.title,
  j.employer_id,
  j.views,
  COUNT(a.id)                                                  AS total_applications,
  COUNT(a.id) FILTER (WHERE a.status = 'shortlisted')         AS shortlisted_count,
  COUNT(a.id) FILTER (WHERE a.status = 'interviewed')         AS interviewed_count,
  COUNT(a.id) FILTER (WHERE a.status = 'offered')             AS offered_count,
  COUNT(a.id) FILTER (WHERE a.status = 'rejected')            AS rejected_count
FROM  jobs j
LEFT JOIN applications a ON a.job_id = j.id
GROUP BY j.id, j.title, j.employer_id, j.views;


-- ============================================================
--  FUNCTION: match_jobs_for_candidate
--  Called by matchingService.js → findMatchingJobsForCandidate()
--
--  Given a candidate's 384-dim embedding, returns up to
--  match_count active jobs ranked by cosine similarity.
--  match_threshold = 0.0 by default – the composite scoring
--  layer in Node.js is the real quality gate.
-- ============================================================
DROP FUNCTION IF EXISTS match_jobs_for_candidate (vector, float, int);

CREATE FUNCTION match_jobs_for_candidate (
  query_embedding  vector(384),
  match_threshold  float   DEFAULT 0.0,
  match_count      integer DEFAULT 20
)
RETURNS TABLE (
  id                  uuid,
  title               text,
  description         text,
  requirements        text,
  skills              text[],
  location            text,
  job_type            text,
  experience_level    text,
  category            text,
  salary_min          integer,
  salary_max          integer,
  is_remote           boolean,
  status              text,
  employer_id         uuid,
  employer_profile_id uuid,
  views               integer,
  created_at          timestamptz,
  updated_at          timestamptz,
  similarity          float
)
LANGUAGE sql STABLE
AS $$
  SELECT
    j.id,
    j.title,
    j.description,
    j.requirements,
    j.skills,
    j.location,
    j.job_type,
    j.experience_level,
    j.category,
    j.salary_min,
    j.salary_max,
    j.is_remote,
    j.status,
    j.employer_id,
    j.employer_profile_id,
    j.views,
    j.created_at,
    j.updated_at,
    (1 - (j.embedding <=> query_embedding))::float AS similarity
  FROM  jobs j
  WHERE j.status    = 'active'
    AND j.embedding IS NOT NULL
    AND (1 - (j.embedding <=> query_embedding)) >= match_threshold
  ORDER BY j.embedding <=> query_embedding   -- cosine distance ASC = similarity DESC
  LIMIT match_count;
$$;


-- ============================================================
--  FUNCTION: match_candidates_for_job
--  Called by matchingService.js → findMatchingCandidatesForJob()
--              and triggerJobMatchingOnPost()
--
--  Given a job's 384-dim embedding, returns up to match_count
--  open-to-work candidates ranked by cosine similarity.
-- ============================================================
DROP FUNCTION IF EXISTS match_candidates_for_job (vector, float, int);

CREATE FUNCTION match_candidates_for_job (
  query_embedding  vector(384),
  match_threshold  float   DEFAULT 0.0,
  match_count      integer DEFAULT 30
)
RETURNS TABLE (
  user_id            uuid,
  headline           text,
  bio                text,
  skills             text[],
  experience_years   integer,
  preferred_location text,
  resume_url         text,
  similarity         float
)
LANGUAGE sql STABLE
AS $$
  SELECT
    cp.user_id,
    cp.headline,
    cp.bio,
    cp.skills,
    cp.experience_years,
    cp.preferred_location,
    cp.resume_url,
    (1 - (cp.embedding <=> query_embedding))::float AS similarity
  FROM  candidate_profiles cp
  WHERE cp.embedding      IS NOT NULL
    AND cp.is_open_to_work = TRUE
    AND (1 - (cp.embedding <=> query_embedding)) >= match_threshold
  ORDER BY cp.embedding <=> query_embedding   -- cosine distance ASC = similarity DESC
  LIMIT match_count;
$$;


-- ============================================================
--  ROW LEVEL SECURITY (RLS)  –  optional but recommended
--  The backend uses the service-role key so RLS is bypassed
--  there.  Enable these if you ever make direct Supabase
--  client calls from the frontend.
-- ============================================================

-- ALTER TABLE users                  ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE candidate_profiles     ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE employer_profiles      ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE jobs                   ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE applications           ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE saved_jobs             ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE notifications          ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE password_reset_tokens  ENABLE ROW LEVEL SECURITY;
